import type {
  VehicleMakeDefinition,
  VehicleModelDefinition,
  VehicleTaxonomyCatalog,
} from "./vehicle-taxonomy";

const DFT_SOURCE_KEY = "dft-veh0160-uk";
const AUDI_BG_SOURCE_KEY = "audi-bg-model-range";

// These canonical families are real, but VEH0160 does not expose an exact
// matching GenModel key for them in the 2026-Q1 file. They remain curated
// AutoMarket entities and deliberately do not claim a DfT source reference.
const dftModelIdsWithoutExactMatch = new Set([
  "AUDI RS 3",
  "AUDI RS 4",
  "AUDI RS 5",
  "AUDI RS 6",
  "AUDI RS 7",
  "BMW I7",
  "BMW IX1",
  "BMW IX2",
  "BYD HAN",
  "BYD SEAL",
  "BYD SEAL U",
  "BYD SEALION 7",
  "BYD TANG",
  "CHEVROLET MALIBU",
  "CITROEN C4 CACTUS",
  "CITROEN C4 PICASSO",
  "CITROEN C5 AIRCROSS",
  "DACIA BIGSTER",
  "DACIA DOKKER",
  "DACIA LODGY",
  "DS DS 3",
  "DS DS 4",
  "DS DS 7",
  "DS DS 9",
  "FIAT 124 SPIDER",
  "FIAT 500L",
  "FIAT 500X",
  "FIAT FREEMONT",
  "HONDA HONDA E",
  "HONDA ZR-V",
  "HYUNDAI IONIQ 6",
  "HYUNDAI IONIQ 9",
  "JAGUAR S-TYPE",
  "JAGUAR X-TYPE",
  "JEEP COMMANDER",
  "KIA EV3",
  "LAND ROVER DISCOVERY SPORT",
  "LEXUS CT",
  "LEXUS ES",
  "LEXUS GS",
  "LEXUS IS",
  "LEXUS LC",
  "LEXUS LM",
  "LEXUS LS",
  "LEXUS NX",
  "LEXUS RC",
  "LEXUS RX",
  "LEXUS UX",
  "MAZDA CX-80",
  "MERCEDES AMG GT",
  "MERCEDES CLE",
  "MERCEDES CLS",
  "MERCEDES G-CLASS",
  "MERCEDES GLS",
  "MERCEDES SL",
  "MERCEDES SLC",
  "MERCEDES SLK",
  "MG MARVEL R",
  "MG MG3",
  "MG MG4",
  "MG MG5",
  "MINI ACEMAN",
  "MITSUBISHI 3000GT",
  "MITSUBISHI ECLIPSE CROSS",
  "NISSAN 350Z",
  "NISSAN 370Z",
  "POLESTAR 3",
  "POLESTAR 4",
  "RENAULT TALISMAN",
  "SKODA ELROQ",
  "SMART #1",
  "SMART #3",
  "SMART #5",
  "SMART ROADSTER",
  "SUBARU CROSSTREK",
  "SUBARU TRIBECA",
  "TESLA CYBERTRUCK",
  "VOLKSWAGEN UP!",
  "VOLVO EX90",
]);

interface ModelSeedOptions
  extends Omit<VehicleModelDefinition, "category" | "name" | "sortOrder"> {
  dftName?: string;
}

type ModelSeed = string | readonly [name: string, options: ModelSeedOptions];

const cars = (
  dftMake: string,
  seeds: readonly ModelSeed[]
): VehicleModelDefinition[] =>
  seeds.map((seed, index) => {
    const [name, options] =
      typeof seed === "string" ? [seed, {}] : [seed[0], seed[1]];
    const dftName = options.dftName ?? `${dftMake} ${name.toUpperCase()}`;
    const { dftName: _dftName, ...modelOptions } = options;

    return {
      ...modelOptions,
      category: "car",
      name,
      sortOrder: index,
      sourceReferences: [
        ...(dftModelIdsWithoutExactMatch.has(dftName)
          ? []
          : [
              {
                externalId: dftName,
                label: dftName,
                sourceKey: DFT_SOURCE_KEY,
              },
            ]),
        ...(modelOptions.sourceReferences ?? []),
      ],
    };
  });

const make = ({
  aliases,
  dftMake,
  models,
  name,
  sortOrder,
}: {
  aliases?: string[];
  dftMake?: string;
  models: VehicleModelDefinition[];
  name: string;
  sortOrder: number;
}): VehicleMakeDefinition => ({
  ...(aliases ? { aliases } : {}),
  models,
  name,
  sortOrder,
  sourceReferences: dftMake
    ? [
        {
          externalId: dftMake,
          label: dftMake,
          sourceKey: DFT_SOURCE_KEY,
        },
      ]
    : [],
});

const audiModels = cars("AUDI", [
  "A3",
  "A1",
  ["Q4 e-tron", { dftName: "AUDI Q4" }],
  "Q2",
  "Q3",
  "Q5",
  "A4",
  "A5",
  "A6",
  ["e-tron", { dftName: "AUDI E-TRON" }],
  ["Q6 e-tron", { dftName: "AUDI Q6 E-TRON" }],
  "Q7",
  "Q8",
  "S3",
  "RS 3",
  "TT",
  "TTS",
  "SQ5",
  "A7",
  "A8",
  "S4",
  "RS 4",
  "S5",
  "RS 5",
  "S6",
  "RS 6",
  "S7",
  "RS 7",
  "SQ7",
  "SQ8",
  "R8",
]);

const audiA3 = audiModels.find((model) => model.name === "A3");
if (audiA3) {
  audiA3.derivatives = [
    {
      bodyType: "hatchback",
      fromYear: 2004,
      name: "Sportback",
      sourceReferences: [
        {
          externalId: "a3-sportback",
          label: "A3 Sportback",
          sourceKey: AUDI_BG_SOURCE_KEY,
        },
      ],
    },
    {
      bodyType: "sedan",
      fromYear: 2013,
      name: "Limousine",
      sourceReferences: [
        {
          externalId: "a3-limousine",
          label: "A3 Limousine",
          sourceKey: AUDI_BG_SOURCE_KEY,
        },
      ],
    },
    {
      bodyType: "hatchback",
      fromYear: 2024,
      name: "allstreet",
      sourceReferences: [
        {
          externalId: "a3-allstreet",
          label: "A3 allstreet",
          sourceKey: AUDI_BG_SOURCE_KEY,
        },
      ],
    },
    {
      bodyType: "convertible",
      fromYear: 2008,
      name: "Cabriolet",
      toYear: 2020,
    },
  ];
  audiA3.generations = [
    { code: "8L", fromYear: 1996, toYear: 2003 },
    { code: "8P", fromYear: 2003, toYear: 2013 },
    { code: "8V", fromYear: 2012, toYear: 2020 },
    { code: "8Y", fromYear: 2020 },
  ];
  audiA3.trims = [
    {
      fromYear: 2024,
      marketCodes: ["BG"],
      name: "Advanced",
      sourceReferences: [
        {
          externalId: "a3-advanced",
          label: "A3 Advanced",
          sourceKey: AUDI_BG_SOURCE_KEY,
        },
      ],
    },
    {
      fromYear: 2024,
      marketCodes: ["BG"],
      name: "S line",
      sourceReferences: [
        {
          externalId: "a3-s-line",
          label: "A3 S line",
          sourceKey: AUDI_BG_SOURCE_KEY,
        },
      ],
    },
  ];
}

export const curatedVehicleTaxonomy = {
  makes: [
    make({
      dftMake: "AUDI",
      models: audiModels,
      name: "Audi",
      sortOrder: 0,
    }),
    make({
      dftMake: "BMW",
      models: cars("BMW", [
        "1 Series",
        "3 Series",
        "2 Series",
        "iX",
        "i4",
        "X1",
        "X3",
        "X5",
        "5 Series",
        "4 Series",
        "X2",
        "M2",
        "M3",
        "M4",
        "i5",
        "i3",
        "7 Series",
        "X4",
        "X6",
        "X7",
        "iX1",
        "iX2",
        "iX3",
        "i7",
        "6 Series",
        "8 Series",
        "Z4",
      ]),
      name: "BMW",
      sortOrder: 1,
    }),
    make({
      dftMake: "MERCEDES",
      models: cars("MERCEDES", [
        ["A-Class", { dftName: "MERCEDES A CLASS" }],
        ["CLA", { dftName: "MERCEDES CLA CLASS" }],
        ["GLA", { dftName: "MERCEDES GLA CLASS" }],
        ["GLC", { dftName: "MERCEDES GLC CLASS" }],
        ["EQA", { dftName: "MERCEDES EQA CLASS" }],
        ["C-Class", { dftName: "MERCEDES C CLASS" }],
        ["GLB", { dftName: "MERCEDES GLB CLASS" }],
        ["EQB", { dftName: "MERCEDES EQB CLASS" }],
        ["GLE", { dftName: "MERCEDES GLE CLASS" }],
        ["EQC", { dftName: "MERCEDES EQC CLASS" }],
        ["E-Class", { dftName: "MERCEDES E CLASS" }],
        ["B-Class", { dftName: "MERCEDES B CLASS" }],
        ["V-Class", { dftName: "MERCEDES V CLASS" }],
        ["EQE", { dftName: "MERCEDES EQE CLASS" }],
        ["S-Class", { dftName: "MERCEDES S CLASS" }],
        ["EQS", { dftName: "MERCEDES EQS CLASS" }],
        "CLS",
        "G-Class",
        "GLS",
        "CLE",
        "SL",
        "SLK",
        "SLC",
        "AMG GT",
      ]),
      name: "Mercedes-Benz",
      sortOrder: 2,
    }),
    make({
      dftMake: "VOLKSWAGEN",
      models: cars("VOLKSWAGEN", [
        "Golf",
        "Polo",
        "Tiguan",
        "T-Roc",
        ["ID.3", { dftName: "VOLKSWAGEN ID3" }],
        "T-Cross",
        ["ID.4", { dftName: "VOLKSWAGEN ID4" }],
        "Taigo",
        "Passat",
        "up!",
        ["ID.5", { dftName: "VOLKSWAGEN ID5" }],
        "Touareg",
        ["ID. Buzz", { dftName: "VOLKSWAGEN ID BUZZ" }],
        "Arteon",
        "Touran",
        "Sharan",
        "Jetta",
        "Scirocco",
        "Beetle",
        "Tayron",
        ["ID.7", { dftName: "VOLKSWAGEN ID7 GTX" }],
      ]),
      name: "Volkswagen",
      sortOrder: 3,
    }),
    make({
      dftMake: "SKODA",
      models: cars("SKODA", [
        "Karoq",
        "Kodiaq",
        "Kamiq",
        "Fabia",
        "Octavia",
        "Enyaq",
        "Superb",
        "Scala",
        "Elroq",
        "Citigo",
        "Yeti",
        "Rapid",
        "Roomster",
        "Felicia",
      ]),
      name: "Skoda",
      sortOrder: 4,
    }),
    make({
      dftMake: "TOYOTA",
      models: cars("TOYOTA", [
        "Yaris",
        "C-HR",
        "Corolla",
        "Aygo",
        "RAV4",
        "Prius",
        ["bZ4X", { dftName: "TOYOTA BZ4X" }],
        "Aygo X",
        ["Land Cruiser", { dftName: "TOYOTA LANDCRUISER" }],
        "GR86",
        "Highlander",
        "Supra",
        "Camry",
        "Avensis",
        "Celica",
        "MR2",
        "Urban Cruiser",
      ]),
      name: "Toyota",
      sortOrder: 5,
    }),
    make({
      dftMake: "FORD",
      models: cars("FORD", [
        "Puma",
        "Kuga",
        "Focus",
        "Fiesta",
        "Explorer",
        "EcoSport",
        "Mustang Mach-E",
        "Capri",
        "Galaxy",
        "Mustang",
        "S-Max",
        "Mondeo",
        "Edge",
        "Ranger",
        "Ka",
        "B-Max",
        "C-Max",
      ]),
      name: "Ford",
      sortOrder: 6,
    }),
    make({
      aliases: ["Vauxhall"],
      dftMake: "VAUXHALL",
      models: cars("VAUXHALL", [
        ["Corsa", { dftName: "VAUXHALL CORSA" }],
        ["Mokka", { dftName: "VAUXHALL MOKKA" }],
        ["Grandland", { dftName: "VAUXHALL GRANDLAND" }],
        ["Crossland", { dftName: "VAUXHALL CROSSLAND" }],
        ["Astra", { dftName: "VAUXHALL ASTRA" }],
        ["Frontera", { dftName: "VAUXHALL FRONTERA" }],
        ["Insignia", { dftName: "VAUXHALL INSIGNIA" }],
        ["Zafira", { dftName: "VAUXHALL ZAFIRA" }],
        "Adam",
        "Meriva",
        "Vectra",
        "Omega",
        "Tigra",
      ]),
      name: "Opel",
      sortOrder: 7,
    }),
    make({
      dftMake: "PEUGEOT",
      models: cars("PEUGEOT", [
        "2008",
        "208",
        "3008",
        "5008",
        "308",
        "408",
        "108",
        "508",
        "207",
        "307",
        "407",
        "RCZ",
      ]),
      name: "Peugeot",
      sortOrder: 8,
    }),
    make({
      dftMake: "RENAULT",
      models: cars("RENAULT", [
        "Clio",
        "Captur",
        "Arkana",
        "Austral",
        "Symbioz",
        "Megane",
        "Scenic",
        "Zoe",
        "Kadjar",
        "Rafale",
        ["5 E-Tech", { dftName: "RENAULT 5 ICONIC E-TECH EV" }],
        ["4 E-Tech", { dftName: "RENAULT 4 ICONIC E-TECH EV" }],
        "Talisman",
        "Laguna",
        "Espace",
        "Modus",
        "Twingo",
      ]),
      name: "Renault",
      sortOrder: 9,
    }),
    make({
      dftMake: "CITROEN",
      models: cars("CITROEN", [
        "C3",
        "C4",
        "C5",
        "C1",
        "Ami",
        "C2",
        "C3 Aircross",
        "C4 Cactus",
        "C4 Picasso",
        "C5 Aircross",
        "C6",
        "C8",
        "DS3",
        "DS4",
        "DS5",
      ]),
      name: "Citroen",
      sortOrder: 10,
    }),
    make({
      dftMake: "DACIA",
      models: cars("DACIA", [
        "Sandero",
        "Duster",
        "Jogger",
        "Spring",
        "Bigster",
        "Logan",
        "Lodgy",
        "Dokker",
      ]),
      name: "Dacia",
      sortOrder: 11,
    }),
    make({
      dftMake: "HYUNDAI",
      models: cars("HYUNDAI", [
        "Tucson",
        "Kona",
        "i10",
        "Ioniq",
        "i20",
        "Bayon",
        "Santa Fe",
        "i30",
        "Inster",
        "Ioniq 5",
        "Ioniq 6",
        "Ioniq 9",
        "Elantra",
        "Sonata",
        "ix20",
        "ix35",
        "Veloster",
      ]),
      name: "Hyundai",
      sortOrder: 12,
    }),
    make({
      dftMake: "KIA",
      models: cars("KIA", [
        "Sportage",
        "Niro",
        "Picanto",
        "Stonic",
        "XCeed",
        "Ceed",
        "EV6",
        "EV3",
        "Sorento",
        "Rio",
        "ProCeed",
        "EV9",
        "EV4",
        "Soul",
        "EV5",
        "Optima",
        "Stinger",
        "Carens",
      ]),
      name: "Kia",
      sortOrder: 13,
    }),
    make({
      dftMake: "NISSAN",
      models: cars("NISSAN", [
        "Qashqai",
        "Juke",
        "X-Trail",
        "Leaf",
        "Ariya",
        "Micra",
        "Note",
        "GT-R",
        "350Z",
        "370Z",
        "Pulsar",
        "Pathfinder",
        "Murano",
        "Almera",
        "Primera",
      ]),
      name: "Nissan",
      sortOrder: 14,
    }),
    make({
      dftMake: "VOLVO",
      models: cars("VOLVO", [
        "XC40",
        "XC60",
        "XC90",
        "EX30",
        "V60",
        "C40",
        "EX40",
        "V90",
        "S60",
        "EX90",
        "S90",
        "EC40",
        "V40",
        "ES90",
        "V70",
        "V50",
        "S80",
      ]),
      name: "Volvo",
      sortOrder: 15,
    }),
    make({
      dftMake: "MAZDA",
      models: cars("MAZDA", [
        "CX-30",
        "CX-5",
        "2",
        "3",
        "CX-60",
        "MX-5",
        "MX-30",
        "6",
        "CX-80",
        "CX-3",
        "RX-7",
        "RX-8",
        "5",
      ]),
      name: "Mazda",
      sortOrder: 16,
    }),
    make({
      dftMake: "HONDA",
      models: cars("HONDA", [
        "Jazz",
        "HR-V",
        "CR-V",
        "Civic",
        "Honda e",
        "ZR-V",
        "Accord",
        "Insight",
        "Prelude",
        "Integra",
        "S2000",
        "NSX",
        "CR-Z",
        "FR-V",
      ]),
      name: "Honda",
      sortOrder: 17,
    }),
    make({
      dftMake: "SUZUKI",
      models: cars("SUZUKI", [
        "Swift",
        "Vitara",
        "SX4",
        "Ignis",
        "S-Cross",
        "Swace",
        "e Vitara",
        "Across",
        "Jimny",
        "Alto",
        "Grand Vitara",
        "Celerio",
        "Baleno",
        "Splash",
      ]),
      name: "Suzuki",
      sortOrder: 18,
    }),
    make({
      dftMake: "MITSUBISHI",
      models: cars("MITSUBISHI", [
        "Outlander",
        "Eclipse Cross",
        "ASX",
        "Space Star",
        "Colt",
        "Lancer",
        "Pajero",
        "L200",
        "Grandis",
        "i-MiEV",
        "3000GT",
      ]),
      name: "Mitsubishi",
      sortOrder: 19,
    }),
    make({
      dftMake: "PORSCHE",
      models: cars("PORSCHE", [
        "Macan",
        "Taycan",
        "911",
        "Cayenne",
        "718",
        "Panamera",
        "Boxster",
        "Cayman",
        "918",
        "928",
        "944",
        "924",
        "968",
      ]),
      name: "Porsche",
      sortOrder: 20,
    }),
    make({
      dftMake: "LEXUS",
      models: cars("LEXUS", [
        "LBX",
        "UX",
        "NX",
        "RX",
        "ES",
        "RZ",
        "CT",
        "LC",
        "LM",
        "LS",
        "RC",
        "IS",
        "GS",
      ]),
      name: "Lexus",
      sortOrder: 21,
    }),
    make({
      dftMake: "LAND ROVER",
      models: cars("LAND ROVER", [
        ["Range Rover Evoque", { dftName: "LAND ROVER RANGE ROVER EVOQUE" }],
        "Defender",
        ["Range Rover Sport", { dftName: "LAND ROVER RANGE ROVER SPORT" }],
        "Discovery",
        ["Range Rover", { dftName: "LAND ROVER RANGE ROVER" }],
        ["Range Rover Velar", { dftName: "LAND ROVER RANGE ROVER VELAR" }],
        "Freelander",
        "Discovery Sport",
      ]),
      name: "Land Rover",
      sortOrder: 22,
    }),
    make({
      dftMake: "JAGUAR",
      models: cars("JAGUAR", [
        "F-Pace",
        "I-Pace",
        "E-Pace",
        "F-Type",
        ["XE", { dftName: "JAGUAR XE SERIES" }],
        ["XF", { dftName: "JAGUAR XF SERIES" }],
        ["XJ", { dftName: "JAGUAR XJ SERIES" }],
        ["XK", { dftName: "JAGUAR XK SERIES" }],
        "S-Type",
        "X-Type",
      ]),
      name: "Jaguar",
      sortOrder: 23,
    }),
    make({
      dftMake: "SEAT",
      models: cars("SEAT", [
        "Arona",
        "Ibiza",
        "Ateca",
        "Leon",
        "Tarraco",
        "Mii",
        "Alhambra",
        "Exeo",
        "Altea",
        "Toledo",
        "Cordoba",
      ]),
      name: "SEAT",
      sortOrder: 24,
    }),
    make({
      dftMake: "CUPRA",
      models: cars("CUPRA", [
        "Formentor",
        "Born",
        "Leon",
        "Terramar",
        "Tavascan",
        "Ateca",
      ]),
      name: "CUPRA",
      sortOrder: 25,
    }),
    make({
      dftMake: "ALFA ROMEO",
      models: cars("ALFA ROMEO", [
        "Tonale",
        "Giulia",
        "Junior",
        "Stelvio",
        "Giulietta",
        "159",
        "156",
        "147",
        "MiTo",
        "Spider",
        "GTV",
        "Brera",
        "4C",
      ]),
      name: "Alfa Romeo",
      sortOrder: 26,
    }),
    make({
      dftMake: "FIAT",
      models: cars("FIAT", [
        "500",
        "600",
        "Panda",
        "Tipo",
        "Grande Panda",
        "500X",
        "500L",
        "Punto",
        "Bravo",
        "Stilo",
        "124 Spider",
        "Croma",
        "Freemont",
      ]),
      name: "Fiat",
      sortOrder: 27,
    }),
    make({
      dftMake: "TESLA",
      models: cars("TESLA", [
        "Model Y",
        "Model 3",
        "Model X",
        "Model S",
        "Roadster",
        "Cybertruck",
      ]),
      name: "Tesla",
      sortOrder: 28,
    }),
    make({
      dftMake: "MINI",
      models: cars("MINI", [
        "Cooper",
        "Countryman",
        "John Cooper Works",
        "Clubman",
        "Aceman",
        "One",
        "Paceman",
      ]),
      name: "MINI",
      sortOrder: 29,
    }),
    make({
      dftMake: "JEEP",
      models: cars("JEEP", [
        "Avenger",
        "Compass",
        "Renegade",
        "Wrangler",
        "Grand Cherokee",
        "Cherokee",
        "Patriot",
        "Commander",
      ]),
      name: "Jeep",
      sortOrder: 30,
    }),
    make({
      dftMake: "SUBARU",
      models: cars("SUBARU", [
        "Forester",
        "Outback",
        "XV",
        "Crosstrek",
        "Impreza",
        "Legacy",
        "BRZ",
        "WRX",
        "Solterra",
        "Tribeca",
      ]),
      name: "Subaru",
      sortOrder: 31,
    }),
    make({
      dftMake: "CHEVROLET",
      models: cars("CHEVROLET", [
        "Captiva",
        "Aveo",
        "Cruze",
        "Spark",
        "Orlando",
        "Camaro",
        "Corvette",
        "Malibu",
        "Trax",
        "Volt",
      ]),
      name: "Chevrolet",
      sortOrder: 32,
    }),
    make({
      dftMake: "SMART",
      models: cars("SMART", [
        "Fortwo",
        "Forfour",
        "#1",
        "#3",
        "#5",
        "Roadster",
      ]),
      name: "Smart",
      sortOrder: 33,
    }),
    make({
      dftMake: "MG",
      models: cars("MG", [
        "MG3",
        "MG4",
        "MG5",
        "ZS",
        "HS",
        "Marvel R",
        "Cyberster",
      ]),
      name: "MG",
      sortOrder: 34,
    }),
    make({
      dftMake: "BYD",
      models: cars("BYD", [
        "Dolphin",
        "Atto 3",
        "Seal",
        "Seal U",
        "Sealion 7",
        "Tang",
        "Han",
      ]),
      name: "BYD",
      sortOrder: 35,
    }),
    make({
      dftMake: "POLESTAR",
      models: cars("POLESTAR", ["2", "3", "4"]),
      name: "Polestar",
      sortOrder: 36,
    }),
    make({
      dftMake: "DS",
      models: cars("DS", ["DS 3", "DS 4", "DS 7", "DS 9"]),
      name: "DS Automobiles",
      sortOrder: 37,
    }),
  ],
  sources: [
    {
      datasetVersion: "2026-Q1",
      key: DFT_SOURCE_KEY,
      kind: "government",
      license: "Open Government Licence v3.0",
      marketCodes: ["GB"],
      name: "UK DfT/DVLA vehicle first registrations (VEH0160)",
      publishedAt: "2026-07-15T00:00:00.000Z",
      url: "https://www.gov.uk/government/statistical-data-sets/vehicle-licensing-statistics-data-files",
    },
    {
      datasetVersion: "2026-07",
      key: AUDI_BG_SOURCE_KEY,
      kind: "manufacturer",
      marketCodes: ["BG"],
      name: "Audi Bulgaria model range",
      url: "https://www.audi.bg/a3",
    },
    {
      datasetVersion: "2026-07-23",
      key: "automarket-curated-eu",
      kind: "curated",
      marketCodes: ["BG", "EU"],
      name: "AutoMarket curated European vehicle taxonomy",
    },
  ],
  version: "automarket-eu-2026-07-23",
} as const satisfies VehicleTaxonomyCatalog;
